services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    hostname: ${PROJECT_PREFIX}
    container_name: ${PROJECT_PREFIX}
    volumes:
      - .:/app
      - ./docker/node/entrypoint.sh:/entrypoint.sh
      - node_modules_volume:/app/code/node_modules
      - ./docker/node/scripts/welcome.sh:/etc/profile.d/welcome.sh:ro
    ports:
      - "${WEB_PORT}:3000"
    working_dir: /app/code
    command: bash /entrypoint.sh
volumes:
  node_modules_volume:
